fix: update sleep days when toy service link is not empty string
toy-land/backend pull request #41
Opened 2021-02-13 04:26 UTC by sypark9646

resolves #40 

## 변경 사항
- 테스트 시 scheduling disable을 위해 `@EnableScheduling` -> ScheduledConfig.java 분리

- UpdatableMaintenance: jpql projection을 위한 interface
- MaintenanceRepository
    - findAllByNeedsHealthCheck() 추가: maintenance와 toy를 inner join 후 toy.service_link가 빈 문자열이 아닌 결과물만 리턴

2021-02-13 05:48 UTC, toneyparky requested changes
깔끔하게 잘 구현해주셨군요..!
연휴인데도 멋져요 정말.

몇가지 이야기 나눠보면 좋을 사항 남겨두었으니 이야기해보아요~

2021-02-13 05:48 UTC, toneyparky commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
현재는 조회와 관련된 테스트기에 디비를 기존 디비로 사용해도 무방하지만 추후에 추가, 제거, 수정과 관련된 테스트가 필요할 때에는 따로 h2와 같은 db를 이용하도록 test-properties.yml을 만들어서 처리해줘야겠다는 생각이 드네요😎
안그러면 기존 디비에 테스트 정보들이 추가되고 제거될테니까요.

혹은 각 테스트 클래스에 `@Transactional`을 달아줘서 [매번 롤백시키는 방법](https://stackoverflow.com/questions/12626502/rollback-transaction-after-test)이 있는 것으로 알고 있어요. 다만 이 경우에 자동으로 생성된 id 값 같은 것도 초기화 되는지를 확인해봐야할 것 같습니다. 또한 기존 디비를 계속 사용할 경우 테스트가 돌 때에는 디비에 lock이 걸릴테니 그동안은 사용자가 사용하더라도 성능적으로 안 좋아질 수 있구요.

가장 깔끔한건 아에 새로운 테스트용 DB를 만드는거 같아요. h2를 사용하는 것도 못 믿는다는 이야기도 들어서요. 같이 이야기를 나눠보죠~

2021-02-13 05:48 UTC, toneyparky commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
위에 부분이 이야기가 되면 이 부분에서도 임의로 에러 요청이 나오는 `ServiceLink`를 넣어두고 테스트할 수 있겠네요.
링크로는 [이 사이트](https://httpstat.us/)를 활용하면 좋을 것 같구요!

이것도 이야기 나눠보죠😊

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/config/ScheduledConfig.java
> +}
분리를 시킨점 좋네요!
스프링을 잘 다루시는 거 같아요.

혹시 분리 시키기 전, 테스트에서 어떤 문제가 있었는지 설명해주신다면 제 학습에 도움이 될 거 같습니다!

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/domain/Maintenance.java
> +@ToString
`Lombok` 사용시 `ToString` 사용을 안해봐서 주의점을 조금 찾아보았습니당

양방향 관계에서 `ToString` 사용시 서로 계속 참조하다가 스택오버플로우가 날 수도 있다고 하는군요. ([링크](https://lkhlkh23.tistory.com/159))
지금은 괜찮지만 추후에 유의하죠!

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
> +    @Query("select m as maintenance, t.githubLink as githubLink, t.serviceLink as serviceLink from Maintenance m inner join Toy t on t.id=m.toyId where t.serviceLink is not null and t.serviceLink <>
당신은 쿼리의 마법사🎩

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/domain/UpdatableMaintenance.java
> +}
요 부분 재미있네요.
`jpql`을 사용할 경우에 이렇게 인터페이스로 빼서 사용하는군요!
저는 `DTO class`를 만들어서 사용하는 경우는 보았습니다.

메서드 네이밍도 재미있구요. `jpql` 을 사용할 경우에 따로 `DTO`에 `getter`에 이렇게 만들 필요 없이 인터페이스로 한방에 처리하는걸 배워갑니다!

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/infra/ApiParser.java
> +        log.info("[health-check]:" + link);
로깅 꼼꼼하십니다👍

2021-02-13 05:48 UTC, toneyparky commented on src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
> +        // TODO: email 링크가 비어 있거나 null일 경우 안 가져오도록
이 부분도 이슈를 파서 진행하죠!
혹은 하고 싶으시다면 여기서 진행해주셔도 괜찮구요😀

우선 이슈는 하나 팔게요~

2021-02-13 13:24 UTC, sypark9646 commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
맞습니다~!! 디비 테스트에 대해 의논 하고 싶은 게 있었는데 이렇게 먼저 말씀해 주셨네요ㅎㅎ 

저는 디비 자체 테스트의 경우 [testContainers](https://www.testcontainers.org/) 써보면 어떨까 생각 했었고,
로직상 repository가 들어갈 때에는 현재 사용하고 있는 `@SpringBootTest` 대신 `@DataJpaTest`를 쓰면 실제 Repository를 쓰되, 인메모리 DB를 쓰기 때문에 롤백을 해 줄 필요 없다고 알고 있습니다.

저희가 컨테이너 환경 배포이기도 하고, DB의 경우 DB마다 isolation, propagation 전략들이 다른데, 
testContainers를 사용하게 되면 현재 프로젝트에서 사용하고 있는 MariaDB 모듈을 동일하게 사용할 수 있더라고요. 
(저도 직접 써보진 않았지만..^^)

단점은 테스트 진행이 느려질 수 있다는점...ㅠㅠ 시간 될 때 이야기 나눠 보아요~

```java
package com.openhack.toyland.domain.toy;

import static org.assertj.core.api.Assertions.*;
import com.openhack.toyland.domain.Organization;
import com.openhack.toyland.domain.OrganizationRepository;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@ActiveProfiles("test")
@Testcontainers
@SpringBootTest
class ToyRepositoryTest {

    @Autowired
    private ToyRepository toyRepository;

    @Autowired
    private OrganizationRepository organizationRepository;

    @Container // DB를 static으로 테스트 전체에 하나만 두고
    static MariaDBContainer mariaDB = new MariaDBContainer().withDatabaseName("toy_land_test");

    @BeforeEach // 테스트 실행 시마다 비워주거나 할 수 있음
    void beforeEach() {
        toyRepository.deleteAll();
        organizationRepository.deleteAll();
    }

    @Test
    /* 테스트 */
}
```

2021-02-13 13:27 UTC, sypark9646 commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
오 굿굿~~!! 좋은 사이트 공유 감사합니다👍👍

2021-02-13 13:28 UTC, sypark9646 commented on src/main/java/com/openhack/toyland/domain/Maintenance.java
> +@ToString
네넵!! 일단은 순환 참조가 일어날 것 같지는 않아서 롬복의 toString을 쓰긴 했으나, 
실제로는 직접 만드는게 더 좋다는 의견도 있어서 흠,,, 잘 모르겠네욥

2021-02-13 13:33 UTC, sypark9646 commented
현재는 service_link가 빈 문자열이 아닐때만 체크하고 있는데
사실 email을 입력하지 않았으면 sleepDays도 셀 필요 없지 않나 하는 생각이 들기도 하고...

뭔가 email을 입력하지 않았다면 메일도 못 받을텐데 -> user는 sleepDays에 대해 모를거고 -> sleepDays가 무한정 커지지 않을까 하는 생각도 들어서 sleepDays를 업데이트 할 때에는 그냥 +1 대신 상한선이 있었으면 좋겠다는 느낌이 들어요😔

2021-02-13 13:45 UTC, sypark9646 commented on src/main/java/com/openhack/toyland/config/ScheduledConfig.java
> +}
스프링은 저도 잘 못다루지만...ㅎㅎ
이전에는 저희가 내부 로직을 실행해 볼 때 cron의 시간을 현재 시간과 가까운 시간에 맞춰서 계속 바꿔가며 테스트 했었잖아요?!
재밌었긴 했지만... 하다 보니 바로바로 내부 로직을 볼 수 있는 테스트를 하나 만드는게 낫겠다 싶어서 만들게 되었구용

저희가 테스트 하고자 하는 `ScheduleService`가 `@Scheduled(cron = "0 0 0 * * *")`에 의해 매일 자정에 동작하는데,
작성한 테스트를 실행할 경우 `@EnableScheduling` 어노테이션을 disable 시킴으로써 자정을 기다리지 않고, 
내부 로직을 바로 실행해 보도록 하기 위해서 ScheduledConfig으로 분리를 했습니다.

`@ConditionalOnProperty`는 지정된 값으로 특정 구성 등록 정보가있는 경우에만 Bean을 등록하는 어노테이션인데,
여기서는 `app.scheduling.enable=true`일 때만 빈 등록을 하기 때문에 테스트에서 `false`를 주면 빈 등록을 안한다 -> scheduled가 동작을 안해서 바로바로 로직을 실행할 수 있다. 요 정도로 이해하면 될 것 같슴당

2021-02-13 13:58 UTC, sypark9646 commented on src/main/java/com/openhack/toyland/domain/UpdatableMaintenance.java
> +}
오호 저는 DTO로 만드는건 첨 알았네요...!! interface로 projection 예시 [공식문서](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections.interfaces)를 보시면 좀 더 좋은 예시가 많은 것 같슴다~

요기서 유의할 점... NullPointerException 에러를 몇개 겪었는데요..
위에 코멘트 다셨던 `@Query`에서 `as maintenance` 로 alias를 안주면 `getMaintenance` 에 맵핑이 안되더라고요😂😂
아직 제대로 알아보기는 전이지만.. join을 하게 되면 select 할 때 alias를 줘야하고, 이 alias 네이밍이 getter 네이밍이랑 같은 걸로 맵핑하게 되는건가? 하는 생각이 들었슴당... 자세한건 저도 좀 더 알아보도록 할게욥~~

2021-02-13 14:08 UTC, sypark9646 commented on src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
> +        // TODO: email 링크가 비어 있거나 null일 경우 안 가져오도록
따로 파는 게 좋을 것 같아서 이슈 새로 팠어요~

2021-02-14 00:51 UTC, toneyparky commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
너무 좋다고 생각해요!
레퍼런스 주신거 찾아봤는데 제가 위에서 언급했던걸 보완해줄 수 있는 친구네요!

물론 언급해주신대로 컨테이너 띄우고 그러는 데에 시간이 걸릴 수 있지만 저는 적용해보면 좋겠다 싶어요!


SpringBootTest와 DataJpaTest는 전자는 모든 빈을 띄우고 후자는 레포지토리와 관련된 빈만 띄우는 걸로 알고 있었는데 인메모리 DB도 사용하고 롤백도 해주는군요! 좋습니다. 아무래도 스프링 자체가 안 띄워지니까 application.yml에 걸려있는 디비 설정들도 다 안먹는 그런 개념인가봐요. [관련된 링크](https://kangwoojin.github.io/programing/auto-configure-test-database/)를 첨부합니다. 

정리하자면 
TO-BE
1. 현재 테스트는 레포지토리 테스트기에 `@DataJpaTest`로 바꾼다. 
2. 예시 적어주신대로 test용 프로퍼티를 만든다. 
3. (필요하다면) 한 줄 위의 링크에서 나온 대로 `@AutoConfigureTestDatabase(replace = Replace.NONE)`를 사용해서 H2를 사용하지 못하게 한다. test용 프로퍼티에서 h2를 안 넣어주면 필요 없을듯하지만 해봐야 알겠군용!
4. `testContainers`를 적용한다.

저는 이렇게 TO-BE를 정리해봤는데 괜찮으신가요?

2021-02-14 00:52 UTC, toneyparky commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
위의 코멘트에서 이야기한대로 적용이 된다면 미리 더미 데이터를 넣어주는 방식으로 테스트 코드를 수정해보죠!

2021-02-14 00:54 UTC, toneyparky commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +@TestPropertySource(properties = "app.scheduling.enable=false")
TO-BE에 따르면 요걸 application-test.yml로 빼면 되겠군용!

2021-02-14 00:54 UTC, toneyparky commented on src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
> +        // TODO: email 링크가 비어 있거나 null일 경우 안 가져오도록
에고 제가 판다해두고 못 팠네요 감사합니다아아
이번 피알이 머지되면 제가 진행하도록하죠

2021-02-14 01:02 UTC, sypark9646 commented on src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
> +    }
굿굿 깔끔하게 정리해 주셨네요~~ 좋습니다

2021-02-14 01:03 UTC, toneyparky approved these changes
언급해주셨던 email 관련해서는 기획의 실수라고 생각합니다.
제가 버그를 발견하고 당장의 버그 수정을 위해서 시야를 짧게 가져갔네요.

조금 더 깊게 생각하고 같이 정책을 세웠어야 했는데 그러지 못해서 일을 두번하게 되는 상황이 발생했네요!

이번 pr을 머지하고 TO-BE로 남긴 부분을 따로 이슈를 팔지 이 pr에서 진행할지에 대해서 이야기 나눠보죠!

2021-02-14 01:03 UTC, toneyparky commented on src/main/java/com/openhack/toyland/config/ScheduledConfig.java
> +}
좋습니다!
재미있긴 했지만.... 사실 저희에게 실제로 필요한건 이런 테스트였죠!!
멋져요

2021-02-14 01:03 UTC, toneyparky commented on src/main/java/com/openhack/toyland/domain/Maintenance.java
> +@ToString
우선은 놔두고 문제가 생긴다면 수정하죠!
해당 클래스에 연관관계가 생길 일은 없어보이니 말이죠!

2021-02-14 01:03 UTC, toneyparky commented on src/main/java/com/openhack/toyland/domain/UpdatableMaintenance.java
> +}
저도 소연님 말씀하시는 흐름에 공감합니다! alias와 getter 네이밍을 찾아서 처리하는 거 같아요!

추가적으로 공식문서 보내주신 부분 아래에는 `DTO`로 넘기는 부분에 대한 설명이 나와있네요!
둘의 차이는 `인터페이스`의 경우 `proxy객체`를 만들어서 처리되는 반면 `DTO`는 그렇지 않다고 하는군요!
> These DTO types can be used in exactly the same way projection interfaces are used, except that no proxying happens and no nested projections can be applied.

재미있네요!

2021-02-14 01:09 UTC, sypark9646 commented
> 이번 pr을 머지하고 TO-BE로 남긴 부분을 따로 이슈를 팔지 이 pr에서 진행할지에 대해서 이야기 나눠보죠!

저는 이슈 따로 파는게 나을 것 같은데 어떠세요?

2021-02-14 01:11 UTC, toneyparky commented
좋습니다!
저도 너무 길어졌다고 생각이 들어서요.
머지할게요~
고생하셨어용

2021-02-14 01:17 UTC, merged